config/routes.rb
Rails.application.routes.draw do
  resources :students, only: [:show, :new, :index, :create]
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/sessions/destroy', to: 'sessions#destroy'

  root 'students#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, :email, :dob, presence: true
  validates :email, uniqueness: true

  validates(:name, {:exclusion => {:in => ['Drop Table', 'Daniel']}})

  validate :must_be_eighteen

  def must_be_eighteen
    # if self.dob
      if self.dob && (Date.today - 18.years < self.dob)
        errors.add(:dob, 'student cannot be a baby')
      end
    # end
  end


  # validate that the email is present x
  # validate that the email is unique

  # validate that the student is atleast 18 yo
  #(Date.today - 18 years is greater than dob)

  # student name cannot be 'Drop Table'
end

app/models/user.rb
require 'digest'
class User < ApplicationRecord

  has_secure_password
  
  # def authenticate(password)
  #   self.password_digest == Digest::SHA256.base64digest(password)
  # end
  #
  # def password=(password)
  #   hashed_pw = Digest::SHA256.base64digest(password)
  #
  #   self.password_digest = hashed_pw
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    # if @current_user
    #   @current_user
    # else
    #   @current_user = User.find_by(id: session[:current_user_id])
    # end
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    !!current_user
  end

  def is_authenticated?
    if !logged_in?
      flash[:message] = 'You must be logged in to view this content'
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    # binding.pry
    @user = User.find_by(username: params[:user][:username])

    if @user && @user.authenticate(params[:user][:password])
      session[:current_user_id] = @user.id
      redirect_to students_path
    else
      flash[:message] = 'That username could not be found in our records'
      redirect_to login_path
    end
  end

  def destroy
    session.clear

    redirect_to login_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :is_authenticated?, except: [:index]

  def index

    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end

  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :dob)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  </head>
  <div class="ui  blue inverted menu">
    <a href="/" class="item">
      <h1>Student Lister</h1>
    </a>
    <div class="right menu">
     <a class="item" href="<%= new_student_path %>">
       Create a New Student
     </a>
     <% if logged_in? %>
       <%= link_to 'Logout', '/sessions/destroy', class: 'item', method: 'delete' %>
    <% else %>
      <a class="item" href="/login">
        Log In
      </a>
    <% end %>
   </div>
  </div>
  <body>
    <div class="ui centered grid ">
      <div class="eight wide column">

        <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/students/index.html.erb
<h1>All Students</h1>
<% if current_user %>
 <h1>Welcome, <%= current_user.username %></h1>
<% end %>
<div class= 'ui huge middle aligned selection divided list'>
  <% @students.each do |student| %>
    <div class="item">
      <%= link_to student.name, student_path(student) %>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>Create a Student</h1>

<% if @student.errors.any? %>
  <div class="ui red inverted segment">
    <ul>

      <% @student.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>

    </ul>
  </div>
<% end %>

<%= form_for(@student, {html: {class: 'ui form'}}) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Enter the students name' %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: 'Email' %>
  </div>
  <div class="field">
    <%= f.label :dob %>
    <%= f.date_field :dob %>
  </div>
  <%= f.submit class: 'massive ui green basic button' %>
<% end %>

app/views/students/show.html.erb
<div class='ui raised segment'>
  <div class='ui fluid card'>
    <div class='huge content'>
      <div class='header'><h1><%= @student.name %></h1></div>
      <div class="meta">
         <span class="date">
           <h3><%= @student.dob.to_date %></h3>
         </span>
      </div>
      <div class="description">
        <h3><%= @student.email %></h3>
      </div>
    </div>
  </div>
</div>